#!/usr/bin/env bash

# Example crontab (user: www-data):
#
# */14 *  * * * /root/spacetrack_tle
#

source_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd "$source_dir"
source credentials

tempfile_cookies=$(mktemp)
tempfile_output=$(mktemp)

# Attempt download from spacetrack.org
wget -q --post-data="identity=${USER}&password=${PASSWORD}&query=https://www.space-track.org/basicspacedata/query/class/tle_latest/NORAD_CAT_ID/25544/ORDINAL/1/EPOCH/%3Enow-30/format/3le" --cookies=on --keep-session-cookies --save-cookies=${tempfile_cookies} 'https://www.space-track.org/ajaxauth/login' -O ${tempfile_output};
if [ $? != 0 ]; then
 rm ${tempfile_output};
 rm ${tempfile_cookies};
 exit 1
fi
rm ${tempfile_cookies};

# Remove spacecraft selector id from name
sed -i 's/0 ISS (ZARYA)/ISS (ZARYA)/' ${tempfile_output};

# Test TLE file
./tlev ${tempfile_output}
if [ $? != 0 ]; then
 rm ${tempfile_output};
 exit 1
fi

# Replace existing tle
mv -f ${tempfile_output} ${OUTPUT_DIR}/iss.txt;
  
